server:
  port: 8082
  address: 0.0.0.0

feign:
  okhttp:
    enabled: true
hm:
  db:
    host: mysql
    pw: root
    database: "hm-cart"
  swagger:
    title: "黑马商城购物车接口"
    desc: "黑马商城购物车接口"
    package: com.hmall.cart.controller